Ex.NO:1 Implement Simple Programs like vector addition in TensorFlow.

AIM : To write a python coding to implement simple programs for vector addition in TensorFlow.

In [4]:
import tensorflow as tf

print("TensorFlow version:", tf.__version__)

# Initialize two constants
x1 = tf.constant([1,2,3,4])
x2 = tf.constant([5,6,7,8])

# Multiply
result = tf.multiply(x1, x2)

# Print the result
print(result)

# Initialize two constants
x1 = tf.constant([1,2,3,4])
x2 = tf.constant([5,6,7,8])

# Multiply
tf.multiply(x1, x2)

# Add a scalar and a list:
x = [1, 2, 3, 4, 5]
y = 1
tf.add(x, y)

# binary + operator
x = tf.convert_to_tensor([1, 2, 3, 4, 5])
y = tf.convert_to_tensor(1)
x + y

# binary * operator
x = tf.convert_to_tensor([1, 2, 3, 4, 5])
y = tf.convert_to_tensor(2)
x * y

# binary - operator
x = tf.convert_to_tensor([1, 2, 3, 4, 5])
y = tf.convert_to_tensor(6)
x - y

scalar = tf.constant(7)

# create a vector
vector = tf.constant([10, 10])

# checking the dimensions of vector
vector.ndim

# creating a matrix
matrix = tf.constant([[1, 2], [3, 4]])
print(matrix)

matrix = tf.constant([[1, 2], [3, 4], [3, 5], [3, 6], [7, 4], [9, 4], [10, 4]])
print(matrix)
print("the number of dimensions of a matrix is:", str(matrix.ndim))

matrix = tf.constant([[1, 2], [3, 4], [3, 5], [3, 6], [7, 4], [9, 4], [10, 4]])
print(matrix)
print("the number of dimensions of a matrix is:", str(matrix.ndim))

matrix = tf.constant([[1, 2, 4], [3, 4, 5], [3, 5, 6], [3, 6, 7], [7, 4, 7], [9, 4, 8], [10, 4, 8]])
print(matrix)
print("the number of dimensions of a matrix is:", str(matrix.ndim))

# creating two tensors
matrix = tf.constant([[1, 2], [3, 4]])
matrix1 = tf.constant([[2, 4], [6, 8]])

# addition of two matrices
print(matrix + matrix1)

# creating two tensors
matrix = tf.constant([[1, 2], [3, 4]])
matrix1 = tf.constant([[2, 4], [6, 8]])
matrix2 = tf.constant([[3, 4], [7, 8]])

# addition of three matrices
print(matrix + matrix1 + matrix2)

# creating two tensors
matrix = tf.constant([[1, 2], [3, 4]])
matrix1 = tf.constant([[2, 4], [6, 8]])

# subtraction of two matrices
print(matrix1 - matrix)

# creating two tensors
matrix = tf.constant([[1, 2], [3, 4]])
matrix1 = tf.constant([[2, 4], [6, 8]])

# multiplication of two matrices
print(matrix1 * matrix)

# creating two tensors
matrix = tf.constant([[1, 2], [3, 4]])
matrix1 = tf.constant([[2, 4], [6, 8]])

# division of two matrices
print(matrix1 / matrix)

# creating a matrix
matrix = tf.constant([[1, 2], [3, 4]])

# transpose of the matrix
print(tf.transpose(matrix))

# creating a matrix
matrix = tf.constant([[1, 2], [3, 4]])

# dot product of matrices
print("dot product of matrices is:", tf.tensordot(matrix, matrix, axes=1))


TensorFlow version: 2.16.1
tf.Tensor([ 5 12 21 32], shape=(4,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 1  2]
 [ 3  4]
 [ 3  5]
 [ 3  6]
 [ 7  4]
 [ 9  4]
 [10  4]], shape=(7, 2), dtype=int32)
the number of dimensions of a matrix is: 2
tf.Tensor(
[[ 1  2]
 [ 3  4]
 [ 3  5]
 [ 3  6]
 [ 7  4]
 [ 9  4]
 [10  4]], shape=(7, 2), dtype=int32)
the number of dimensions of a matrix is: 2
tf.Tensor(
[[ 1  2  4]
 [ 3  4  5]
 [ 3  5  6]
 [ 3  6  7]
 [ 7  4  7]
 [ 9  4  8]
 [10  4  8]], shape=(7, 3), dtype=int32)
the number of dimensions of a matrix is: 2
tf.Tensor(
[[ 3  6]
 [ 9 12]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 6 10]
 [16 20]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 2  8]
 [18 32]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[2. 2.]
 [2. 2.]], shape=(2, 2), dtype=float64)
tf.Tensor(
[[1 3]
 [2 4]], shape=(2, 2), dtype=int32)
dot product of matrices is: tf.Tensor(
[[ 7 10]
 [15 22]], shape=(2,